env:
  es6: true
  node: true
rules:
  # Errors
  no-var: error
  strict:
    - error
    - global
  # Warnings
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - windows
  quotes:
    - warn
    - double
  semi:
    - warn
    - always